add github cli
rpmfusion-infra/fedy pull request #69
Opened 2020-10-27 02:21 UTC by danniel-lara

Adicionei essa nova ferramenta cli do github

2020-10-27 02:33 UTC, MalteKiefer requested changes
Please fix the typo

2020-10-27 02:33 UTC, MalteKiefer commented on plugins/githubcli.plugin/metadata.json
> +	"description": "GitHub on the command lin",
Please fix the typo

2020-10-27 06:33 UTC, kwizart commented on plugins/githubcli.plugin/uninstall.sh
> +  dnf -y remove gh
It's possible that gh-cli.repo to be removed by hand. So it's unrelated to the availability of the gh package.
Please move the dnf remove out of the gh-cli.repo test condition.

2021-03-12 13:03 UTC, kwizart commented
@danniel-lara Can you fix the two points ?

2021-10-21 07:21 UTC, merged